name: vdt.simpleaptrepo ci
on: [push]
jobs:
  run-linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Setup Python 3.6
      uses: actions/setup-python@v2
      with:
         python-version: '3.6'
    - name: Install all dependencies
      run: make install
    - name: Run all linting
      run: make lint

  run-tests:
    needs: run-linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
           python-version: ${{ matrix.python-version }}
      - name: Install all dependencies
        run: make install-dev
      - name: Run the unittests
        run: make test