name: vdt.simpleaptrepo ci
on: [push]

defaults:
  run:
    working-directory: ./src

jobs:
  run-linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        path: ./src
    - name: Setup Python 3.6
      uses: actions/setup-python@v2
      with:
         python-version: '3.6'
    - name: Install all dependencies
      run: make install
    - name: Run all linting
      run: make lint
    - name: Upload src dir as artefact
      uses: actions/upload-artifact@v2
      with:
        name: src
        path: ./src

  run-tests:
    needs: run-linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Download src dir
        uses: actions/download-artifact@v2
        with:
          name: src
          path: ./src
      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
           python-version: ${{ matrix.python-version }}
      - name: Install all dependencies
        run: make install-dev
      - name: Run the unittests
        run: make test

  run-docker:
    needs: run-tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /usr/local/src
    container:
      image: maerteijn/simpeapt-test-image:latest
    steps:
      - name: Download src dir
        uses: actions/download-artifact@v2
        with:
          name: src
          path: /usr/local/src
      - name: Copy GPG keys to github home directory
        run: cp -R /root/.gnupg ~
      - name: Create a test repo and install a signed package
        run: bash ./docker/create-test-repo.sh
